In [786]:
import numpy as np
import pandas as pd

### Matching based on Volumes
* Volume bins
    * 100 - 150
    * 150 - 200
    * 200 - 250
    * 250 - 300

In [787]:
# Load demographics file
df_demographics = pd.read_csv('/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv')
# df_demographics
df_demographics_volumes = df_demographics.as_matrix(['SITE_NAME','VOLUMES']).squeeze()
df_demographics_volumes

array([['CALTECH', 150.0],
       ['CMU', 240.0],
       ['KKI', 156.0],
       ['LEUVEN_1', 250.0],
       ['LEUVEN_2', 250.0],
       ['MAX_MUN', 120.0],
       ['NYU', 180.0],
       ['OHSU', 82.0],
       ['OLIN', 210.0],
       ['PITT', 200.0],
       ['SBL', 200.0],
       ['SDSU', 180.0],
       ['STANFORD', 180.0],
       ['TRINITY', 150.0],
       ['UCLA_1', 120.0],
       ['UCLA_2', 120.0],
       ['UM_1', 300.0],
       ['UM_2', 300.0],
       ['USM', 240.0],
       ['YALE', 200.0]], dtype=object)

In [788]:
df_phenotype = pd.read_csv('/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv') # , index_col='SUB_ID'
df_phenotype = df_phenotype.sort_values(['SUB_ID'])

volumes_bins = np.array([[0,150],[151,200],[201,250],[251,300]])

bins_volumes_AUT = []
bins_volumes_TD = []

for counter, _bin in enumerate(volumes_bins):
    df_demographics_volumes_selected_bin = df_demographics_volumes[np.where(np.logical_and((df_demographics_volumes[:,1] >= _bin[0]),(df_demographics_volumes[:,1] <= _bin[1])))]


    selected_AUT = pd.DataFrame()
    selected_TD = pd.DataFrame()
    for site in df_demographics_volumes_selected_bin:
        print(site[0])
        selected_AUT = pd.concat([selected_AUT,df_phenotype.loc[(df_phenotype['SEX'] == 1) & (df_phenotype['DSM_IV_TR'] == 1) & (df_phenotype['SITE_ID'] == site[0])]])  
        selected_TD = pd.concat([selected_AUT,df_phenotype.loc[(df_phenotype['SEX'] == 1) & (df_phenotype['DSM_IV_TR'] == 0) & (df_phenotype['SITE_ID'] == site[0])]])  

    bins_volumes_AUT.append(selected_AUT)
    bins_volumes_TD.append(selected_TD)

CALTECH
MAX_MUN
OHSU
TRINITY
UCLA_1
UCLA_2
KKI
NYU
PITT
SBL
SDSU
STANFORD
YALE
CMU
LEUVEN_1
LEUVEN_2
OLIN
USM
UM_1
UM_2

In [789]:
f = bins_volumes_AUT[0]
# f.loc[[2,3,4,5]]
f

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
2,CALTECH,51458,1,1,39.20,1,R,NaN,93.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,CALTECH,51459,1,1,22.80,1,R,NaN,106.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
8,CALTECH,51464,1,1,20.90,1,Ambi,NaN,101.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
9,CALTECH,51465,1,1,20.20,1,R,NaN,96.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
10,CALTECH,51466,1,1,27.60,1,Ambi,NaN,106.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
11,CALTECH,51467,1,1,23.40,1,R,NaN,93.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
12,CALTECH,51468,1,1,20.10,1,R,NaN,100.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
16,CALTECH,51472,1,1,17.50,1,Ambi,NaN,125.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
17,CALTECH,51473,1,1,21.20,1,R,NaN,-9999.0,-9999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
18,CALTECH,51474,1,1,20.90,1,R,NaN,100.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
217,MAX_MUN,51350,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
218,MAX_MUN,51351,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
659,TRINITY,50239,1,1,17.03,1,R,NaN,97.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
661,TRINITY,50241,1,1,17.17,1,R,NaN,89.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
662,TRINITY,50242,1,1,12.75,1,R,NaN,117.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
663,TRINITY,50243,1,1,13.75,1,R,NaN,90.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
665,TRINITY,50245,1,1,21.58,1,R,NaN,72.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
666,TRINITY,50246,1,1,19.50,1,R,NaN,105.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
668,TRINITY,50248,1,1,13.58,1,R,NaN,117.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
669,TRINITY,50249,1,1,13.83,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
670,TRINITY,50250,1,1,13.91,1,R,NaN,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
671,TRINITY,50251,1,1,17.25,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
701,UCLA_1,51201,1,1,13.52,1,R,NaN,104.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.52,NaN
702,UCLA_1,51202,1,1,11.56,1,R,NaN,98.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.56,NaN
703,UCLA_1,51203,1,1,13.37,1,R,NaN,103.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.37,NaN
704,UCLA_1,51204,1,1,14.57,1,R,NaN,98.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.57,NaN
705,UCLA_1,51205,1,1,17.94,1,R,NaN,102.0,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.94,NaN
706,UCLA_1,51206,1,1,15.78,1,R,NaN,102.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.78,NaN
708,UCLA_1,51208,1,1,16.98,1,L,NaN,113.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.27,NaN
709,UCLA_1,51209,1,1,9.99,1,R,NaN,128.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9.99,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,UCLA_1,51232,1,1,15.79,1,R,NaN,89.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
733,UCLA_1,51233,1,1,12.75,1,R,NaN,79.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
734,UCLA_1,51234,1,1,10.91,1,R,NaN,87.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.91,NaN
735,UCLA_1,51235,1,1,10.67,1,R,NaN,132.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.67,NaN
736,UCLA_1,51236,1,1,12.42,1,R,NaN,89.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.42,NaN
737,UCLA_1,51237,1,1,17.40,1,R,NaN,100.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.40,NaN
738,UCLA_1,51238,1,1,10.85,1,R,NaN,73.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.64,NaN
739,UCLA_1,51239,1,1,13.67,1,R,NaN,86.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.67,NaN
740,UCLA_1,51240,1,1,14.96,1,R,NaN,121.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.40,NaN
741,UCLA_1,51241,1,1,10.90,1,R,NaN,95.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.03,NaN
743,UCLA_1,51243,1,1,11.69,1,R,NaN,101.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
744,UCLA_1,51244,1,1,13.09,1,R,NaN,-9999.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
745,UCLA_1,51245,1,1,14.98,1,R,NaN,64.0,59.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
746,UCLA_1,51246,1,1,13.10,1,R,NaN,84.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
747,UCLA_1,51247,1,1,11.97,1,R,NaN,118.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
748,UCLA_1,51248,1,1,13.50,1,R,NaN,110.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.50,NaN
749,UCLA_1,51249,1,1,8.49,1,R,NaN,107.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,8.49,NaN
783,UCLA_2,51291,1,1,16.47,1,R,NaN,86.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.63,NaN
784,UCLA_2,51292,1,1,12.24,1,R,NaN,75.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.24,NaN
785,UCLA_2,51293,1,1,13.08,1,R,NaN,92.0,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.08,NaN
786,UCLA_2,51294,1,1,11.70,1,R,NaN,87.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.06,NaN
787,UCLA_2,51295,1,1,10.04,1,L,NaN,108.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.33,NaN
788,UCLA_2,51296,1,1,11.16,1,R,NaN,77.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.16,NaN
789,UCLA_2,51297,1,1,14.27,1,L,NaN,88.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.27,NaN
790,UCLA_2,51298,1,1,10.57,1,R,NaN,118.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.69,NaN
791,UCLA_2,51299,1,1,14.77,1,R,NaN,104.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.77,NaN
792,UCLA_2,51300,1,1,14.08,1,L,NaN,92.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.08,NaN
793,UCLA_2,51301,1,1,13.28,1,R,NaN,91.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.28,NaN
794,UCLA_2,51302,1,1,10.85,1,R,NaN,87.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.85,NaN
809,UCLA_2,51317,1,1,12.82,1,R,NaN,102.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.82,NaN

In [790]:
f.iloc[[1,2,3,10]]

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
3,CALTECH,51459,1,1,22.8,1,R,NaN,106.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
8,CALTECH,51464,1,1,20.9,1,Ambi,NaN,101.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
9,CALTECH,51465,1,1,20.2,1,R,NaN,96.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
217,MAX_MUN,51350,1,1,11.0,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [791]:
# num_bins = 4
print('Range    ','TD ','AUT ','Ratio TD/AUT')
ratio = np.zeros((len(bins_volumes_AUT)))
for i in range(len(bins_volumes_AUT)):
    ratio[i] = bins_volumes_TD[i].shape[0]/bins_volumes_AUT[i].shape[0]
    print(volumes_bins[i],bins_volumes_TD[i].shape[0],bins_volumes_AUT[i].shape[0], ratio[i])

Range     TD  AUT  Ratio TD/AUT
[  0 150] 89 77 1.15584415584
[151 200] 110 90 1.22222222222
[201 250] 137 94 1.45744680851
[251 300] 69 48 1.4375

In [792]:
min_ratio = np.min(ratio)
min_index = np.argmin(ratio)

In [793]:
min_ratio = 5.0
new_TD = np.zeros((len(bins_volumes_AUT)))
print('Range    ','TD ','AUT ')
for i in range(len(bins_volumes_AUT)):
    new_TD[i] = np.ceil(bins_volumes_AUT[i].shape[0] * min_ratio)
    print(volumes_bins[i],new_TD[i],bins_volumes_AUT[i].shape[0])

Range     TD  AUT
[  0 150] 385.0 77
[151 200] 450.0 90
[201 250] 470.0 94
[251 300] 240.0 48

In [794]:
# Now loop over all the bins created and select the specific number of subjects randomly from each TD bin

TD_idx_list = []
selected_df_TD = pd.DataFrame()

for i in range(len(bins_volumes_TD)):
    idx = np.arange(len(bins_volumes_TD[i]))
    np.random.shuffle(idx)
    idx = idx[0:int(new_TD[i])]
    TD_idx_list.append(idx)
    selected_df_TD = pd.concat([selected_df_TD, bins_volumes_TD[i].iloc[idx]])
    
selected_df_TD= selected_df_TD.sort_values(['SUB_ID'])
    
    
    
#     print(idx)

### Note

In [795]:
id_x = np.arange(10)
# id_x[11] # will give error out of bounds
id_x[0:100] # will not give error and give the whole array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [796]:
# Sanity check that two bins have no subject in common -  empty output means correct
# set(bins_volumes_TD[0].as_matrix(['SUB_ID']).squeeze()) - (set(bins_volumes_TD[0].as_matrix(['SUB_ID']).squeeze()) - set(bins_volumes_TD[1].as_matrix(['SUB_ID']).squeeze()))

In [797]:
# Sanity check to see of no subjects are repeated
# subid = selected_df_TD.sort_values(['SUB_ID']).as_matrix(['SUB_ID']).squeeze()
# len(np.unique(subid)) == len(subid)

In [798]:
# Sanity check to see of the number of subjects are same as expected
# len(subid) == (89 + 105 + 109 + 56)

In [799]:
#  Sanity check so that no subject index is repeated
# len(np.unique(TD_idx_list[3]))  == len(TD_idx_list[3] )

# sanity check to check the new number of TD subjects in each Volumes bin
# len(TD_idx_list[3]) == 56

In [800]:
selected_df_TD

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
489,PITT,50002,1,1,16.77,1,Ambi,NaN,103.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
490,PITT,50003,1,1,24.45,1,R,NaN,124.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
491,PITT,50004,1,1,19.09,1,R,NaN,113.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
493,PITT,50006,1,1,13.37,1,L,NaN,109.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
494,PITT,50007,1,1,17.78,1,R,NaN,110.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
495,PITT,50008,1,1,32.45,1,R,NaN,123.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
496,PITT,50009,1,1,33.86,1,R,NaN,126.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
497,PITT,50010,1,1,35.20,1,L,NaN,81.0,81.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
498,PITT,50011,1,1,16.93,1,L,NaN,111.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
499,PITT,50012,1,1,21.48,1,R,NaN,128.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
500,PITT,50013,1,1,9.33,1,R,NaN,86.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
501,PITT,50014,1,1,14.20,1,R,NaN,96.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
502,PITT,50015,1,1,14.20,1,R,NaN,99.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
503,PITT,50016,1,1,21.82,1,R,NaN,123.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
504,PITT,50017,1,1,22.70,1,R,NaN,87.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
505,PITT,50019,1,1,27.81,1,R,NaN,100.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
506,PITT,50020,1,1,20.83,1,R,NaN,100.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
507,PITT,50022,1,1,16.99,1,R,NaN,119.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
509,PITT,50024,1,1,22.64,1,R,NaN,127.0,121.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
510,PITT,50025,1,1,31.72,1,R,NaN,131.0,132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
511,PITT,50026,1,1,16.28,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
512,PITT,50027,1,1,12.24,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
513,PITT,50028,1,1,12.74,1,R,NaN,126.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
515,PITT,50053,1,1,12.03,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
516,PITT,50055,1,1,16.99,1,R,NaN,111.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
517,PITT,50056,1,1,13.59,1,R,NaN,113.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
577,SDSU,50183,1,1,14.14,1,R,NaN,139.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
586,SDSU,50192,1,1,12.99,1,R,NaN,85.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
659,TRINITY,50239,1,1,17.03,1,R,NaN,97.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
661,TRINITY,50241,1,1,17.17,1,R,NaN,89.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,UCLA_2,51300,1,1,14.08,1,L,NaN,92.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.08,NaN
793,UCLA_2,51301,1,1,13.28,1,R,NaN,91.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.28,NaN
794,UCLA_2,51302,1,1,10.85,1,R,NaN,87.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.85,NaN
796,UCLA_2,51304,2,0,10.53,1,R,NaN,120.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.53,NaN
798,UCLA_2,51306,2,0,11.66,1,R,NaN,119.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.66,NaN
799,UCLA_2,51307,2,0,12.15,1,R,NaN,128.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.15,NaN
800,UCLA_2,51308,2,0,9.79,1,R,NaN,124.0,125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.08,NaN
801,UCLA_2,51309,2,0,11.90,1,R,NaN,107.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.93,NaN
802,UCLA_2,51310,2,0,11.70,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,-9999.00,NaN
803,UCLA_2,51311,2,0,11.95,1,R,NaN,103.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.95,NaN
804,UCLA_2,51312,2,0,12.90,1,R,NaN,123.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.90,NaN
805,UCLA_2,51313,2,0,13.36,1,R,NaN,112.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.36,NaN
806,UCLA_2,51314,2,0,13.12,1,R,NaN,97.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.12,NaN
807,UCLA_2,51315,2,0,13.63,1,R,NaN,118.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.63,NaN
808,UCLA_2,51316,2,0,12.66,1,L,NaN,94.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.66,NaN
809,UCLA_2,51317,1,1,12.82,1,R,NaN,102.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.82,NaN
217,MAX_MUN,51350,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
218,MAX_MUN,51351,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
2,CALTECH,51458,1,1,39.20,1,R,NaN,93.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
3,CALTECH,51459,1,1,22.80,1,R,NaN,106.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
8,CALTECH,51464,1,1,20.90,1,Ambi,NaN,101.0,118.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
9,CALTECH,51465,1,1,20.20,1,R,NaN,96.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
10,CALTECH,51466,1,1,27.60,1,Ambi,NaN,106.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
11,CALTECH,51467,1,1,23.40,1,R,NaN,93.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
12,CALTECH,51468,1,1,20.10,1,R,NaN,100.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
16,CALTECH,51472,1,1,17.50,1,Ambi,NaN,125.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
17,CALTECH,51473,1,1,21.20,1,R,NaN,-9999.0,-9999.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
18,CALTECH,51474,1,1,20.90,1,R,NaN,100.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
561,SBL,51571,1,1,22.00,1,NaN,-90.0,-9999.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,22.45
575,SBL,51585,1,1,27.00,1,NaN,90.0,96.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,-9999.00

### Matching based on Age
* Age bins
    * 6 - 9
    * 9 -12
    * 12 - 15
    * 15 - 18

In [801]:
age_bins = np.array([[0,9],[9,12],[12,15],[15,18]])

bins_age_AUT = []
bins_age_TD = []

# for counter, _bin in enumerate(age_bins):



for age in age_bins:
    
    selected_AUT = pd.DataFrame()
    selected_TD = pd.DataFrame()

    
    print(age[0], age[1])
    selected_AUT = pd.concat([selected_AUT,df_phenotype.loc[(df_phenotype['SEX'] == 1) 
                                                            & (df_phenotype['DSM_IV_TR'] == 1)
                                                            & (df_phenotype['AGE_AT_SCAN'] > age[0])
                                                            & (df_phenotype['AGE_AT_SCAN'] <= age[1]) ]])  
    selected_TD = pd.concat([selected_TD,selected_df_TD.loc[(selected_df_TD['SEX'] == 1)
                                                            & (selected_df_TD['DSM_IV_TR'] == 0)
                                                            & (selected_df_TD['AGE_AT_SCAN'] > age[0])
                                                            & (selected_df_TD['AGE_AT_SCAN'] <= age[1]) ]])  

    bins_age_AUT.append(selected_AUT)
    bins_age_TD.append(selected_TD)

0 9
9 12
12 15
15 18

In [802]:
bins_age_TD[0]

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
976,USM,50453,2,0,8.7721,1,NaN,85.19,121.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1059,YALE,50554,2,0,8.6700,1,R,NaN,99.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1069,YALE,50564,2,0,7.6600,1,R,NaN,140.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN

In [803]:
# num_bins = 4
print('Original data stats')
print('Age Range    ','TD ','AUT ','Ratio TD/AUT')
ratio = np.zeros((len(bins_age_TD)))
for i in range(len(bins_age_TD)):
    ratio[i] = bins_age_TD[i].shape[0]/bins_age_AUT[i].shape[0]
    print(age_bins[i],bins_age_TD[i].shape[0],bins_age_AUT[i].shape[0], ratio[i])

Original data stats
Age Range     TD  AUT  Ratio TD/AUT
[0 9] 3 15 0.2
[ 9 12] 16 59 0.271186440678
[12 15] 27 85 0.317647058824
[15 18] 19 55 0.345454545455

In [804]:
min_ratio = np.min(ratio)
min_index = np.argmin(ratio)

In [805]:
new_TD = np.zeros((len(bins_age_AUT)))
print('Matched data stats')
print('Age Range    ','TD ','AUT ')
for i in range(len(bins_age_AUT)):
    new_TD[i] = np.ceil(bins_age_AUT[i].shape[0] * min_ratio)
    print(age_bins[i],new_TD[i],bins_age_AUT[i].shape[0])

Matched data stats
Age Range     TD  AUT
[0 9] 3.0 15
[ 9 12] 12.0 59
[12 15] 17.0 85
[15 18] 11.0 55

In [806]:
# Now loop over all the bins created and select the specific number of subjects randomly from each TD bin

TD_idx_list = []
selected_df_TD = pd.DataFrame()

for i in range(len(bins_age_TD)):
    idx = np.arange(len(bins_age_TD[i]))
    np.random.shuffle(idx)
    idx = idx[0:int(new_TD[i])]
    TD_idx_list.append(idx)
    selected_df_TD = pd.concat([selected_df_TD, bins_age_TD[i].iloc[idx]])
    
selected_df_TD = selected_df_TD.sort_values(['SUB_ID'])
    
    
    
#     print(idx)

In [807]:
selected_df_TD

# selected_df_TD.as_matrix(['SUB_ID']).squeeze()

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
921,UM_2,50383,2,0,14.4000,1,R,NaN,116.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
922,UM_2,50385,2,0,17.8000,1,R,NaN,109.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
923,UM_2,50386,2,0,17.8000,1,R,NaN,129.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
926,UM_2,50390,2,0,14.5000,1,R,NaN,103.5,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
942,UM_2,50415,2,0,17.6000,1,R,NaN,111.5,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
943,UM_2,50416,2,0,14.8000,1,R,NaN,108.5,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
944,UM_2,50417,2,0,13.3000,1,L,NaN,121.5,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
945,UM_2,50418,2,0,14.9000,1,R,NaN,112.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
946,UM_2,50419,2,0,15.8000,1,R,NaN,111.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
949,UM_2,50423,2,0,14.1000,1,R,NaN,111.5,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
950,UM_2,50424,2,0,17.9000,1,R,NaN,125.5,136.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
952,UM_2,50426,2,0,13.6000,1,R,NaN,113.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
953,UM_2,50427,2,0,15.8000,1,R,NaN,96.0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
954,UM_2,50428,2,0,15.5000,1,R,NaN,89.5,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
959,USM,50436,2,0,13.8097,1,NaN,86.67,126.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
961,USM,50438,2,0,15.0253,1,NaN,80.00,97.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
970,USM,50447,2,0,12.9391,1,NaN,80.00,130.0,132.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
971,USM,50448,2,0,10.4668,1,NaN,73.33,144.0,140.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
974,USM,50451,2,0,12.5257,1,NaN,100.00,109.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
976,USM,50453,2,0,8.7721,1,NaN,85.19,121.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
984,USM,50461,2,0,16.3943,1,NaN,80.00,113.0,105.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
987,USM,50464,2,0,9.9548,1,NaN,100.00,119.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
993,USM,50470,2,0,9.9165,1,NaN,80.00,106.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1057,YALE,50552,2,0,12.7500,1,R,NaN,106.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1058,YALE,50553,2,0,9.7500,1,R,NaN,127.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1059,YALE,50554,2,0,8.6700,1,R,NaN,99.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1061,YALE,50556,2,0,10.6700,1,R,NaN,78.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1064,YALE,50559,2,0,12.2500,1,R,NaN,123.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1069,YALE,50564,2,0,7.6600,1,R,NaN,140.0,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1075,YALE,50570,2,0,16.6600,1,L,NaN,88.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1076,YALE,50571,2,0,11.0000,1,R,NaN,92.0,91.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1078,YALE,50573,2,0,14.1700,1,R,NaN,103.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1079,YALE,50574,2,0,10.9200,1,R,NaN,91.0,103.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1080,YALE,50575,2,0,14.0000,1,R,NaN,120.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
1082,YALE,50577,2,0,15.2500,1,R,NaN,73.0,73.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
796,UCLA_2,51304,2,0,10.5300,1,R,NaN,120.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.53,NaN
798,UCLA_2,51306,2,0,11.6600,1,R,NaN,119.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.66,NaN
799,UCLA_2,51307,2,0,12.1500,1,R,NaN,128.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.15,NaN
801,UCLA_2,51309,2,0,11.9000,1,R,NaN,107.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.93,NaN
802,UCLA_2,51310,2,0,11.7000,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,-9999.00,NaN
803,UCLA_2,51311,2,0,11.9500,1,R,NaN,103.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.95,NaN
804,UCLA_2,51312,2,0,12.9000,1,R,NaN,123.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.90,NaN
806,UCLA_2,51314,2,0,13.1200,1,R,NaN,97.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.12,NaN

In [808]:
x = np.arange(10)
np.random.shuffle(x)

In [809]:
x

array([3, 0, 1, 2, 4, 7, 5, 9, 6, 8])

In [810]:
48 * min_ratio

9.6000000000000014

In [811]:
#     selected = selected.loc[(selected['SEX'] == 1) & (selected['DSM_IV_TR'] == 0) & (selected['SITE_ID'] == site[0]) & (selected['EYE_STATUS_AT_SCAN'] == 1)]

In [812]:
# selected;

In [813]:
df_phenotype.loc[(df_phenotype['SEX'] == 1) & (df_phenotype['DSM_IV_TR'] == 0) & (df_phenotype['SITE_ID'] == 'TRINITY') & (df_phenotype['EYE_STATUS_AT_SCAN'] == 1)]

Empty DataFrame
Columns: [SITE_ID, SUB_ID, DX_GROUP, DSM_IV_TR, AGE_AT_SCAN, SEX, HANDEDNESS_CATEGORY, HANDEDNESS_SCORES, FIQ, VIQ, PIQ, FIQ_TEST_TYPE, VIQ_TEST_TYPE, PIQ_TEST_TYPE, ADI_R_SOCIAL_TOTAL_A, ADI_R_VERBAL_TOTAL_BV, ADI_RRB_TOTAL_C, ADI_R_ONSET_TOTAL_D, ADI_R_RSRCH_RELIABLE, ADOS_MODULE, ADOS_TOTAL, ADOS_COMM, ADOS_SOCIAL, ADOS_STEREO_BEHAV, ADOS_RSRCH_RELIABLE, ADOS_GOTHAM_SOCAFFECT, ADOS_GOTHAM_RRB, ADOS_GOTHAM_TOTAL, ADOS_GOTHAM_SEVERITY, SRS_VERSION, SRS_RAW_TOTAL, SRS_AWARENESS, SRS_COGNITION, SRS_COMMUNICATION, SRS_MOTIVATION, SRS_MANNERISMS, SCQ_TOTAL, AQ_TOTAL, COMORBIDITY, CURRENT_MED_STATUS, MEDICATION_NAME, OFF_STIMULANTS_AT_SCAN, VINELAND_RECEPTIVE_V_SCALED, VINELAND_EXPRESSIVE_V_SCALED, VINELAND_WRITTEN_V_SCALED, VINELAND_COMMUNICATION_STANDARD, VINELAND_PERSONAL_V_SCALED, VINELAND_DOMESTIC_V_SCALED, VINELAND_COMMUNITY_V_SCALED, VINELAND_DAILYLVNG_STANDARD, VINELAND_INTERPERSONAL_V_SCALED, VINELAND_PLAY_V_SCALED, VINELAND_COPING_V_SCALED, VINELAND_SOCIAL_STANDARD, VINELAND_SUM_SCORES, VINELAND_ABC_STANDARD, VINELAND_INFORMANT, WISC_IV_VCI, WISC_IV_PRI, WISC_IV_WMI, WISC_IV_PSI, WISC_IV_SIM_SCALED, WISC_IV_VOCAB_SCALED, WISC_IV_INFO_SCALED, WISC_IV_BLK_DSN_SCALED, WISC_IV_PIC_CON_SCALED, WISC_IV_MATRIX_SCALED, WISC_IV_DIGIT_SPAN_SCALED, WISC_IV_LET_NUM_SCALED, WISC_IV_CODING_SCALED, WISC_IV_SYM_SCALED, EYE_STATUS_AT_SCAN, AGE_AT_MPRAGE, BMI]
Index: []

[0 rows x 74 columns]

## Create a function to do volumes matching

In [814]:
def volumes_matching(volumes_bins, df_demographics, df_TD_phenotype, df_AUT_phenotype):
    # Load demographics file
    
#     demographics_file_path = '/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv'
#     phenotype_file_path = '/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv'
#     volumes_bins = np.array([[0,150],[151,200],[201,250],[251,300]])
    
    
#     df_demographics = pd.read_csv(demographics_file_path)
    df_demographics_volumes = df_demographics.as_matrix(['SITE_NAME','VOLUMES']).squeeze()


    
#     df_phenotype = pd.read_csv(phenotype_file_path) 
#     df_phenotype = df_phenotype.sort_values(['SUB_ID'])

    

    bins_volumes_AUT_data = []
    bins_volumes_TD_data = []

    for counter, _bin in enumerate(volumes_bins):
        df_demographics_volumes_selected_bin = df_demographics_volumes[np.where(np.logical_and((df_demographics_volumes[:,1] >= _bin[0]),(df_demographics_volumes[:,1] <= _bin[1])))]


        selected_AUT = pd.DataFrame()
        selected_TD = pd.DataFrame()
        for site in df_demographics_volumes_selected_bin:
#             print(site[0])
            selected_AUT = pd.concat([selected_AUT,df_AUT_phenotype.loc[(df_AUT_phenotype['SEX'] == 1)
                                                                    & (df_AUT_phenotype['DSM_IV_TR'] == 1)
                                                                    & (df_AUT_phenotype['SITE_ID'] == site[0])]])  
            selected_TD = pd.concat([selected_TD,df_TD_phenotype.loc[(df_TD_phenotype['SEX'] == 1)
                                                                      & (df_TD_phenotype['DSM_IV_TR'] == 0)
                                                                      & (df_TD_phenotype['SITE_ID'] == site[0])]])  

        bins_volumes_AUT_data.append(selected_AUT)
        bins_volumes_TD_data.append(selected_TD)
        
    matched_df_TD,matched_df_AUT = matching(volumes_bins, bins_volumes_TD_data, bins_volumes_AUT_data)
#     sub_ids = selected_df_TD.as_matrix(['SUB_ID']).squeeze()
    matched_df_TD.to_csv('volumes_matched_TD.csv')
    return matched_df_TD,matched_df_AUT

In [815]:
def matching_old(bins, bins_TD_data, bins_AUT_data):
    # num_bins = 4
    print('Original data stats')
    print('Range    ','TD ','AUT ','Ratio TD/AUT')
    ratio = np.zeros((len(bins_TD_data)))
    for i in range(len(bins_TD_data)):
        ratio[i] = bins_TD_data[i].shape[0]/bins_AUT_data[i].shape[0]
        print(bins[i],bins_TD_data[i].shape[0],bins_AUT_data[i].shape[0], ratio[i])

    min_ratio = np.min(ratio)
    min_index = np.argmin(ratio)
    
    new_TD = np.zeros((len(bins_TD_data)))

    print('Matched data stats')
    print('Range    ','TD ','AUT ')
    for i in range(len(bins_TD_data)):
        new_TD[i] = np.floor(bins_AUT_data[i].shape[0] * min_ratio)
        print(bins[i],new_TD[i],bins_AUT_data[i].shape[0])

    # Now loop over all the bins created and select the specific number of subjects randomly from each TD bin

    TD_idx_list = []
    selected_df_TD = pd.DataFrame()

    for i in range(len(bins_TD_data)):
        idx = np.arange(len(bins_TD_data[i]))
        np.random.shuffle(idx)
        idx = idx[0:int(new_TD[i])]
        TD_idx_list.append(idx)
        selected_df_TD = pd.concat([selected_df_TD, bins_TD_data[i].iloc[idx]])

    matched_df_TD = selected_df_TD.sort_values(['SUB_ID'])

    return matched_df_TD

In [816]:
def matching(bins, bins_TD_data, bins_AUT_data, randomize = False):
    # num_bins = 4
    print('Original data stats')
    print('Range    ','TD ','AUT ','Ratio TD/AUT')
    ratio = np.zeros((len(bins_TD_data)))
    for i in range(len(bins_TD_data)):
        ratio[i] = bins_TD_data[i].shape[0]/bins_AUT_data[i].shape[0]
        print(bins[i],bins_TD_data[i].shape[0],bins_AUT_data[i].shape[0], ratio[i])

    min_ratio = np.min(ratio)
    min_index = np.argmin(ratio)
    
    new_TD = np.zeros((len(bins_TD_data)))
    new_AUT = np.zeros((len(bins_AUT_data)))
    
#     matched_df_AUT = None
#     matched_df_TD = None
    if min_ratio < 1:
        _ratio = 1.0 / ratio
#         min_index = np.argmin(_ratio)
        min_ratio = np.min(_ratio)
#       
#    -------------------------------------------
        print('Matched data stats')
        print('Range    ','TD ','AUT ')
        for i in range(len(bins_TD_data)):
            new_AUT[i] = np.floor(bins_TD_data[i].shape[0] * min_ratio)
            print(bins[i],bins_TD_data[i].shape[0],new_AUT[i])

        # Now loop over all the bins created and select the specific number of subjects randomly from each TD bin

#         AUT_idx_list = []
        selected_df_AUT = pd.DataFrame()
        selected_df_TD = pd.DataFrame()
        

        for i in range(len(bins_AUT_data)):
            idx = np.arange(len(bins_AUT_data[i]))
            if randomize == True:
                np.random.shuffle(idx)
            idx = idx[0:int(new_AUT[i])]
#             AUT_idx_list.append(idx)
            selected_df_AUT = pd.concat([selected_df_AUT, bins_AUT_data[i].iloc[idx]])
            selected_df_TD = pd.concat([selected_df_TD, bins_TD_data[i]])

        matched_df_AUT = selected_df_AUT.sort_values(['SUB_ID'])
        matched_df_TD = selected_df_TD.sort_values(['SUB_ID'])
        
        return matched_df_TD, matched_df_AUT


#     -------------------------------------
    
    print('Matched data stats')
    print('Range    ','TD ','AUT ')
    for i in range(len(bins_TD_data)):
        new_TD[i] = np.floor(bins_AUT_data[i].shape[0] * min_ratio)
        print(bins[i],new_TD[i],bins_AUT_data[i].shape[0])

    # Now loop over all the bins created and select the specific number of subjects randomly from each TD bin

#     TD_idx_list = []
    selected_df_TD = pd.DataFrame()
    selected_df_AUT = pd.DataFrame()
        

    for i in range(len(bins_TD_data)):
        idx = np.arange(len(bins_TD_data[i]))
        np.random.shuffle(idx)
        idx = idx[0:int(new_TD[i])]
#         TD_idx_list.append(idx)
        selected_df_TD = pd.concat([selected_df_TD, bins_TD_data[i].iloc[idx]])
        selected_df_AUT = pd.concat([selected_df_AUT, bins_AUT_data[i]])

    matched_df_TD = selected_df_TD.sort_values(['SUB_ID'])
    matched_df_AUT = selected_df_AUT.sort_values(['SUB_ID'])

    return matched_df_TD,matched_df_AUT

In [817]:
demographics_file_path = '/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv'
phenotype_file_path = '/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv'

df_demographics = pd.read_csv(demographics_file_path)


df_phenotype = pd.read_csv(phenotype_file_path) 
df_phenotype = df_phenotype.sort_values(['SUB_ID'])

volumes_bins = np.array([[0,150],[151,200],[201,250],[251,300]])

matched_df_TD,matched_df_AUT = volumes_matching(volumes_bins, df_demographics, df_phenotype, df_phenotype)

Original data stats
Range     TD  AUT  Ratio TD/AUT
[  0 150] 110 77 1.42857142857
[151 200] 177 90 1.96666666667
[201 250] 114 94 1.21276595745
[251 300] 59 48 1.22916666667
Matched data stats
Range     TD  AUT
[  0 150] 93.0 77
[151 200] 109.0 90
[201 250] 114.0 94
[251 300] 58.0 48

In [818]:
def age_matching(age_bins, df_TD_phenotype, df_AUT_phenotype ):
#     age_bins = np.array([[0,9],[9,12],[12,15],[15,18]])

    bins_age_AUT_data = []
    bins_age_TD_data = []

    # for counter, _bin in enumerate(age_bins):



    for age in age_bins:

        selected_AUT = pd.DataFrame()
        selected_TD = pd.DataFrame()


#         print(age[0], age[1])
        selected_AUT = pd.concat([selected_AUT,df_AUT_phenotype.loc[(df_AUT_phenotype['SEX'] == 1) 
                                                                & (df_AUT_phenotype['DSM_IV_TR'] == 1)
                                                                & (df_AUT_phenotype['AGE_AT_SCAN'] > age[0])
                                                                & (df_AUT_phenotype['AGE_AT_SCAN'] <= age[1]) ]])  
        selected_TD = pd.concat([selected_TD,df_TD_phenotype.loc[(df_TD_phenotype['SEX'] == 1)
                                                                & (df_TD_phenotype['DSM_IV_TR'] == 0)
                                                                & (df_TD_phenotype['AGE_AT_SCAN'] > age[0])
                                                                & (df_TD_phenotype['AGE_AT_SCAN'] <= age[1]) ]])  

        bins_age_AUT_data.append(selected_AUT)
        bins_age_TD_data.append(selected_TD)
        
    matched_df_TD,matched_df_AUT = matching(age_bins, bins_age_TD_data, bins_age_AUT_data)
#     sub_ids = selected_df_TD.as_matrix(['SUB_ID']).squeeze()
    matched_df_TD.to_csv('age_matched_TD.csv')
    return matched_df_TD,matched_df_AUT

In [819]:
demographics_file_path = '/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv'
phenotype_file_path = '/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv'

df_demographics = pd.read_csv(demographics_file_path)


df_phenotype = pd.read_csv(phenotype_file_path) 
df_phenotype = df_phenotype.sort_values(['SUB_ID'])

age_bins = np.array([[0,9],[9,12],[12,15],[15,18]])

matched_df_TD,matched_df_AUT = age_matching(age_bins, matched_df_TD, df_phenotype)

Original data stats
Range     TD  AUT  Ratio TD/AUT
[0 9] 9 15 0.6
[ 9 12] 62 59 1.05084745763
[12 15] 85 85 1.0
[15 18] 78 55 1.41818181818
Matched data stats
Range     TD  AUT
[0 9] 9 6.0
[ 9 12] 62 43.0
[12 15] 85 59.0
[15 18] 78 54.0

## TR Matching

In [820]:
def tr_matching(TR_bins, df_demographics, df_TD_phenotype, df_AUT_phenotype ):    
#     df_demographics = pd.read_csv(demographics_file_path)
    df_demographics_TR = df_demographics.as_matrix(['SITE_NAME','TR']).squeeze()



#     df_phenotype = pd.read_csv(phenotype_file_path) 
#     df_phenotype = df_TD_phenotype.sort_values(['SUB_ID'])



    bins_TR_AUT_data = []
    bins_TR_TD_data = []

    for counter, _bin in enumerate(TR_bins):
        df_demographics_TR_selected_bin = df_demographics_TR[np.where(np.logical_and((df_demographics_TR[:,1] > _bin[0]),(df_demographics_TR[:,1] <= _bin[1])))]


        selected_AUT = pd.DataFrame()
        selected_TD = pd.DataFrame()
        for site in df_demographics_TR_selected_bin:
    #             print(site[0])
            selected_AUT = pd.concat([selected_AUT,df_AUT_phenotype.loc[(df_AUT_phenotype['SEX'] == 1)
                                                                    & (df_AUT_phenotype['DSM_IV_TR'] == 1)
                                                                    & (df_AUT_phenotype['SITE_ID'] == site[0])]])  
            selected_TD = pd.concat([selected_TD,df_TD_phenotype.loc[(df_TD_phenotype['SEX'] == 1)
                                                                      & (df_TD_phenotype['DSM_IV_TR'] == 0)
                                                                      & (df_TD_phenotype['SITE_ID'] == site[0])]])  

        bins_TR_AUT_data.append(selected_AUT)
        bins_TR_TD_data.append(selected_TD)

    matched_df_TD, matched_df_AUT = matching(TR_bins, bins_TR_TD_data, bins_TR_AUT_data)
    #     sub_ids = selected_df_TD.as_matrix(['SUB_ID']).squeeze()
    matched_df_TD.to_csv('TR_matched_TD.csv')
    return matched_df_TD, matched_df_AUT

In [821]:
demographics_file_path = '/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv'
phenotype_file_path = '/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv'
TR_bins = np.array([[0,2],[2,2.5],[2.5,3.0]])


df_demographics = pd.read_csv(demographics_file_path)
df_phenotype = pd.read_csv(phenotype_file_path) 
df_phenotype = df_phenotype.sort_values(['SUB_ID'])

matched_df_TD = tr_matching(TR_bins,df_demographics, matched_df_TD, df_phenotype)

Original data stats
Range     TD  AUT  Ratio TD/AUT
[ 0.  2.] 183 240 0.7625
[ 2.   2.5] 12 12 1.0
[ 2.5  3. ] 39 57 0.684210526316
Matched data stats
Range     TD  AUT
[ 0.  2.] 183 183.0
[ 2.   2.5] 12 12.0
[ 2.5  3. ] 39 39.0

In [822]:
# Combined Matching

demographics_file_path = '/home1/varunk/Autism-Connectome-Analysis-brain_connectivity/notebooks/demographics.csv'
phenotype_file_path = '/home1/varunk/data/ABIDE1/RawDataBIDs/composite_phenotypic_file.csv'
df_demographics = pd.read_csv(demographics_file_path)
df_phenotype = pd.read_csv(phenotype_file_path) 
df_phenotype = df_phenotype.sort_values(['SUB_ID'])



# Volume matching
print('Volume Matching')
volumes_bins = np.array([[0,150],[151,200],[201,250],[251,300]])
matched_df_TD = df_phenotype
matched_df_AUT = df_phenotype
matched_df_TD, matched_df_AUT = volumes_matching(volumes_bins, df_demographics, matched_df_TD, matched_df_AUT)

Volume Matching
Original data stats
Range     TD  AUT  Ratio TD/AUT
[  0 150] 110 77 1.42857142857
[151 200] 177 90 1.96666666667
[201 250] 114 94 1.21276595745
[251 300] 59 48 1.22916666667
Matched data stats
Range     TD  AUT
[  0 150] 93.0 77
[151 200] 109.0 90
[201 250] 114.0 94
[251 300] 58.0 48

In [823]:
matched_df_TD.shape,matched_df_AUT.shape

((374, 74), (309, 74))

In [824]:
# TR matching
print('TR Matching')
TR_bins = np.array([[0,2],[2,2.5],[2.5,3.0]])
# matched_df_TD = df_phenotype
# matched_df_AUT = df_phenotype
matched_df_TD,matched_df_AUT = tr_matching(TR_bins,df_demographics, matched_df_TD, matched_df_AUT)

TR Matching
Original data stats
Range     TD  AUT  Ratio TD/AUT
[ 0.  2.] 292 240 1.21666666667
[ 2.   2.5] 25 12 2.08333333333
[ 2.5  3. ] 57 57 1.0
Matched data stats
Range     TD  AUT
[ 0.  2.] 240.0 240
[ 2.   2.5] 12.0 12
[ 2.5  3. ] 57.0 57

In [825]:
matched_df_TD.shape,matched_df_AUT.shape

((309, 74), (309, 74))

In [826]:
# Age Matching
print('Age Matching')
age_bins = np.array([[0,9],[9,12],[12,15],[15,18]])
# matched_df_TD = df_phenotype
# matched_df_AUT = df_phenotype
matched_df_TD,matched_df_AUT = age_matching(age_bins, matched_df_TD, matched_df_AUT)

# 94.0 77
# [151 200] 110.0 90
# [201 250] 115.0 94
# [251 300] 59.0 48

Age Matching
Original data stats
Range     TD  AUT  Ratio TD/AUT
[0 9] 9 15 0.6
[ 9 12] 48 59 0.813559322034
[12 15] 79 85 0.929411764706
[15 18] 58 55 1.05454545455
Matched data stats
Range     TD  AUT
[0 9] 9 8.0
[ 9 12] 48 45.0
[12 15] 79 74.0
[15 18] 58 55.0

In [827]:
matched_df_TD.shape,matched_df_AUT.shape

((194, 74), (182, 74))

(204, 162)

In [829]:
matched_df_AUT

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
489,PITT,50002,1,1,16.77,1,Ambi,NaN,103.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
493,PITT,50006,1,1,13.37,1,L,NaN,109.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
494,PITT,50007,1,1,17.78,1,R,NaN,110.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
498,PITT,50011,1,1,16.93,1,L,NaN,111.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
500,PITT,50013,1,1,9.33,1,R,NaN,86.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
501,PITT,50014,1,1,14.20,1,R,NaN,96.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
502,PITT,50015,1,1,14.20,1,R,NaN,99.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
507,PITT,50022,1,1,16.99,1,R,NaN,119.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
511,PITT,50026,1,1,16.28,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
512,PITT,50027,1,1,12.24,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
513,PITT,50028,1,1,12.74,1,R,NaN,126.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
515,PITT,50053,1,1,12.03,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
516,PITT,50055,1,1,16.99,1,R,NaN,111.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
517,PITT,50056,1,1,13.59,1,R,NaN,113.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
577,SDSU,50183,1,1,14.14,1,R,NaN,139.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
586,SDSU,50192,1,1,12.99,1,R,NaN,85.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
659,TRINITY,50239,1,1,17.03,1,R,NaN,97.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
661,TRINITY,50241,1,1,17.17,1,R,NaN,89.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
662,TRINITY,50242,1,1,12.75,1,R,NaN,117.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
663,TRINITY,50243,1,1,13.75,1,R,NaN,90.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
668,TRINITY,50248,1,1,13.58,1,R,NaN,117.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
669,TRINITY,50249,1,1,13.83,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
670,TRINITY,50250,1,1,13.91,1,R,NaN,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
671,TRINITY,50251,1,1,17.25,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
810,UM_1,50272,1,1,14.20,1,R,NaN,98.5,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
811,UM_1,50273,1,1,16.80,1,R,NaN,112.5,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
812,UM_1,50274,1,1,14.20,1,R,NaN,111.5,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
813,UM_1,50275,1,1,11.50,1,L,NaN,85.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
815,UM_1,50277,1,1,15.40,1,L,NaN,107.5,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
817,UM_1,50279,1,1,12.20,1,R,NaN,87.5,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,UCLA_1,51222,1,1,11.81,1,R,NaN,113.0,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.81,NaN
725,UCLA_1,51225,1,1,12.33,1,R,NaN,111.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.33,NaN
729,UCLA_1,51229,1,1,14.59,1,R,NaN,95.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.59,NaN
731,UCLA_1,51231,1,1,10.28,1,R,NaN,103.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.01,NaN
732,UCLA_1,51232,1,1,15.79,1,R,NaN,89.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
733,UCLA_1,51233,1,1,12.75,1,R,NaN,79.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
734,UCLA_1,51234,1,1,10.91,1,R,NaN,87.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.91,NaN
735,UCLA_1,51235,1,1,10.67,1,R,NaN,132.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.67,NaN
736,UCLA_1,51236,1,1,12.42,1,R,NaN,89.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.42,NaN
737,UCLA_1,51237,1,1,17.40,1,R,NaN,100.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.40,NaN
738,UCLA_1,51238,1,1,10.85,1,R,NaN,73.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.64,NaN
740,UCLA_1,51240,1,1,14.96,1,R,NaN,121.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.40,NaN
741,UCLA_1,51241,1,1,10.90,1,R,NaN,95.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.03,NaN
744,UCLA_1,51244,1,1,13.09,1,R,NaN,-9999.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
747,UCLA_1,51247,1,1,11.97,1,R,NaN,118.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
748,UCLA_1,51248,1,1,13.50,1,R,NaN,110.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.50,NaN
783,UCLA_2,51291,1,1,16.47,1,R,NaN,86.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.63,NaN
784,UCLA_2,51292,1,1,12.24,1,R,NaN,75.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.24,NaN
786,UCLA_2,51294,1,1,11.70,1,R,NaN,87.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.06,NaN
787,UCLA_2,51295,1,1,10.04,1,L,NaN,108.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.33,NaN
789,UCLA_2,51297,1,1,14.27,1,L,NaN,88.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.27,NaN
790,UCLA_2,51298,1,1,10.57,1,R,NaN,118.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.69,NaN
791,UCLA_2,51299,1,1,14.77,1,R,NaN,104.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.77,NaN
792,UCLA_2,51300,1,1,14.08,1,L,NaN,92.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.08,NaN
793,UCLA_2,51301,1,1,13.28,1,R,NaN,91.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.28,NaN
794,UCLA_2,51302,1,1,10.85,1,R,NaN,87.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.85,NaN
809,UCLA_2,51317,1,1,12.82,1,R,NaN,102.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.82,NaN
217,MAX_MUN,51350,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
218,MAX_MUN,51351,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
16,CALTECH,51472,1,1,17.50,1,Ambi,NaN,125.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN

In [830]:
matched_df_TD

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
520,PITT,50031,2,0,12.92,1,R,NaN,106.0,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
524,PITT,50035,2,0,17.36,1,R,NaN,107.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
532,PITT,50043,2,0,13.78,1,R,NaN,113.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
533,PITT,50044,2,0,17.13,1,R,NaN,110.0,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
534,PITT,50045,2,0,15.70,1,R,NaN,114.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
537,PITT,50048,2,0,11.81,1,R,NaN,107.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
480,OLIN,50102,2,0,14.00,1,R,NaN,103.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
477,OLIN,50103,2,0,14.00,1,R,NaN,106.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
476,OLIN,50104,2,0,16.00,1,R,NaN,125.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
485,OLIN,50106,2,0,10.00,1,R,NaN,129.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
483,OLIN,50110,2,0,13.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
478,OLIN,50111,2,0,14.00,1,R,NaN,118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
487,OLIN,50112,2,0,17.00,1,R,NaN,102.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
474,OLIN,50116,2,0,15.00,1,R,NaN,115.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
456,OLIN,50118,1,0,15.00,1,R,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
465,OLIN,50120,1,0,15.00,1,R,NaN,103.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
454,OLIN,50122,1,0,12.00,1,L,NaN,112.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
457,OLIN,50123,1,0,17.00,1,R,NaN,135.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
461,OLIN,50124,1,0,18.00,1,R,NaN,100.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
467,OLIN,50128,1,0,16.00,1,R,NaN,114.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
455,OLIN,50129,1,0,12.00,1,R,NaN,108.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
466,OLIN,50132,1,0,16.00,1,R,NaN,-9999.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
459,OLIN,50134,1,0,18.00,1,L,NaN,124.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
587,SDSU,50193,2,0,14.75,1,R,NaN,112.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
588,SDSU,50194,2,0,13.35,1,L,NaN,110.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
589,SDSU,50195,2,0,12.58,1,R,NaN,123.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
590,SDSU,50196,2,0,12.91,1,R,NaN,110.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
591,SDSU,50197,2,0,14.98,1,R,NaN,109.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
593,SDSU,50199,2,0,15.53,1,R,NaN,100.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
594,SDSU,50200,2,0,13.88,1,R,NaN,108.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,UCLA_1,51263,2,0,16.03,1,R,NaN,87.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.03,NaN
765,UCLA_1,51265,2,0,15.92,1,R,NaN,108.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.92,NaN
766,UCLA_1,51266,2,0,14.03,1,R,NaN,108.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.03,NaN
768,UCLA_1,51268,2,0,17.78,1,R,NaN,105.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.78,NaN
769,UCLA_1,51269,2,0,14.29,1,R,NaN,94.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.29,NaN
770,UCLA_1,51270,2,0,11.08,1,R,NaN,117.0,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.08,NaN
771,UCLA_1,51271,2,0,12.09,1,R,NaN,113.0,121.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.09,NaN
772,UCLA_1,51272,2,0,13.41,1,R,NaN,84.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.41,NaN
773,UCLA_1,51273,2,0,12.68,1,R,NaN,104.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.68,NaN
774,UCLA_1,51274,2,0,10.96,1,R,NaN,125.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.96,NaN
775,UCLA_1,51275,2,0,15.74,1,R,NaN,106.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.74,NaN
776,UCLA_1,51276,2,0,13.85,1,R,NaN,105.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.03,NaN
781,UCLA_1,51281,2,0,11.83,1,R,NaN,108.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.91,NaN
796,UCLA_2,51304,2,0,10.53,1,R,NaN,120.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.53,NaN
798,UCLA_2,51306,2,0,11.66,1,R,NaN,119.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.66,NaN
799,UCLA_2,51307,2,0,12.15,1,R,NaN,128.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.15,NaN
800,UCLA_2,51308,2,0,9.79,1,R,NaN,124.0,125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.08,NaN
802,UCLA_2,51310,2,0,11.70,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,-9999.00,NaN
803,UCLA_2,51311,2,0,11.95,1,R,NaN,103.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.95,NaN
804,UCLA_2,51312,2,0,12.90,1,R,NaN,123.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.90,NaN
805,UCLA_2,51313,2,0,13.36,1,R,NaN,112.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.36,NaN
806,UCLA_2,51314,2,0,13.12,1,R,NaN,97.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.12,NaN
807,UCLA_2,51315,2,0,13.63,1,R,NaN,118.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.63,NaN
808,UCLA_2,51316,2,0,12.66,1,L,NaN,94.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.66,NaN
223,MAX_MUN,51356,2,0,10.00,1,R,NaN,129.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
224,MAX_MUN,51357,2,0,11.00,1,R,NaN,110.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
225,MAX_MUN,51358,2,0,10.00,1,R,NaN,113.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
226,MAX_MUN,51359,2,0,13.00,1,R,NaN,101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
228,MAX_MUN,51361,2,0,16.00,1,R,NaN,114.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
31,CALTECH,51487,2,0,17.00,1,R,NaN,113.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN

In [837]:
matched_df_TD.loc[(matched_df_TD['SEX'] == 1) & (matched_df_TD['DSM_IV_TR'] == 0)].shape

(194, 74)

In [838]:
matched_df_AUT.loc[(matched_df_AUT['SEX'] == 1) & (matched_df_AUT['DSM_IV_TR'] == 1)].shape

(182, 74)

In [831]:
matched_df_TD.loc[(matched_df_TD['SEX'] == 1) & (matched_df_TD['DSM_IV_TR'] == 0) & (matched_df_TD['EYE_STATUS_AT_SCAN'] == 1) ].shape

(153, 74)

In [832]:
matched_df_AUT.loc[(matched_df_AUT['SEX'] == 1) & (matched_df_AUT['DSM_IV_TR'] == 1) & (matched_df_AUT['EYE_STATUS_AT_SCAN'] == 1) ].shape

(145, 74)

In [833]:
type(matched_df_AUT),type(matched_df_TD)

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

In [834]:
matched_df_TD.notnull().any(axis = 0)

SITE_ID                             True
SUB_ID                              True
DX_GROUP                            True
DSM_IV_TR                           True
AGE_AT_SCAN                         True
SEX                                 True
HANDEDNESS_CATEGORY                 True
HANDEDNESS_SCORES                   True
FIQ                                 True
VIQ                                 True
PIQ                                 True
FIQ_TEST_TYPE                       True
VIQ_TEST_TYPE                       True
PIQ_TEST_TYPE                       True
ADI_R_SOCIAL_TOTAL_A               False
ADI_R_VERBAL_TOTAL_BV              False
ADI_RRB_TOTAL_C                    False
ADI_R_ONSET_TOTAL_D                False
ADI_R_RSRCH_RELIABLE               False
ADOS_MODULE                         True
ADOS_TOTAL                          True
ADOS_COMM                           True
ADOS_SOCIAL                         True
ADOS_STEREO_BEHAV                   True
ADOS_RSRCH_RELIABLE                False
ADOS_GOTHAM_SOCAFFECT               True
ADOS_GOTHAM_RRB                     True
ADOS_GOTHAM_TOTAL                   True
ADOS_GOTHAM_SEVERITY                True
SRS_VERSION                         True
                                   ...
VINELAND_WRITTEN_V_SCALED           True
VINELAND_COMMUNICATION_STANDARD     True
VINELAND_PERSONAL_V_SCALED          True
VINELAND_DOMESTIC_V_SCALED          True
VINELAND_COMMUNITY_V_SCALED         True
VINELAND_DAILYLVNG_STANDARD         True
VINELAND_INTERPERSONAL_V_SCALED     True
VINELAND_PLAY_V_SCALED              True
VINELAND_COPING_V_SCALED            True
VINELAND_SOCIAL_STANDARD            True
VINELAND_SUM_SCORES                 True
VINELAND_ABC_STANDARD               True
VINELAND_INFORMANT                  True
WISC_IV_VCI                         True
WISC_IV_PRI                         True
WISC_IV_WMI                         True
WISC_IV_PSI                         True
WISC_IV_SIM_SCALED                  True
WISC_IV_VOCAB_SCALED                True
WISC_IV_INFO_SCALED                 True
WISC_IV_BLK_DSN_SCALED              True
WISC_IV_PIC_CON_SCALED              True
WISC_IV_MATRIX_SCALED               True
WISC_IV_DIGIT_SPAN_SCALED           True
WISC_IV_LET_NUM_SCALED              True
WISC_IV_CODING_SCALED               True
WISC_IV_SYM_SCALED                  True
EYE_STATUS_AT_SCAN                  True
AGE_AT_MPRAGE                       True
BMI                                 True
Length: 74, dtype: bool

In [835]:
matched_df_TD

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
520,PITT,50031,2,0,12.92,1,R,NaN,106.0,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
524,PITT,50035,2,0,17.36,1,R,NaN,107.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
532,PITT,50043,2,0,13.78,1,R,NaN,113.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
533,PITT,50044,2,0,17.13,1,R,NaN,110.0,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
534,PITT,50045,2,0,15.70,1,R,NaN,114.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
537,PITT,50048,2,0,11.81,1,R,NaN,107.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
480,OLIN,50102,2,0,14.00,1,R,NaN,103.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
477,OLIN,50103,2,0,14.00,1,R,NaN,106.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
476,OLIN,50104,2,0,16.00,1,R,NaN,125.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
485,OLIN,50106,2,0,10.00,1,R,NaN,129.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
483,OLIN,50110,2,0,13.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
478,OLIN,50111,2,0,14.00,1,R,NaN,118.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
487,OLIN,50112,2,0,17.00,1,R,NaN,102.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
474,OLIN,50116,2,0,15.00,1,R,NaN,115.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
456,OLIN,50118,1,0,15.00,1,R,NaN,80.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
465,OLIN,50120,1,0,15.00,1,R,NaN,103.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
454,OLIN,50122,1,0,12.00,1,L,NaN,112.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
457,OLIN,50123,1,0,17.00,1,R,NaN,135.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
461,OLIN,50124,1,0,18.00,1,R,NaN,100.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
467,OLIN,50128,1,0,16.00,1,R,NaN,114.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
455,OLIN,50129,1,0,12.00,1,R,NaN,108.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
466,OLIN,50132,1,0,16.00,1,R,NaN,-9999.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
459,OLIN,50134,1,0,18.00,1,L,NaN,124.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
587,SDSU,50193,2,0,14.75,1,R,NaN,112.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
588,SDSU,50194,2,0,13.35,1,L,NaN,110.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
589,SDSU,50195,2,0,12.58,1,R,NaN,123.0,111.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
590,SDSU,50196,2,0,12.91,1,R,NaN,110.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
591,SDSU,50197,2,0,14.98,1,R,NaN,109.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
593,SDSU,50199,2,0,15.53,1,R,NaN,100.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
594,SDSU,50200,2,0,13.88,1,R,NaN,108.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,UCLA_1,51263,2,0,16.03,1,R,NaN,87.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.03,NaN
765,UCLA_1,51265,2,0,15.92,1,R,NaN,108.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.92,NaN
766,UCLA_1,51266,2,0,14.03,1,R,NaN,108.0,107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.03,NaN
768,UCLA_1,51268,2,0,17.78,1,R,NaN,105.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.78,NaN
769,UCLA_1,51269,2,0,14.29,1,R,NaN,94.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.29,NaN
770,UCLA_1,51270,2,0,11.08,1,R,NaN,117.0,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.08,NaN
771,UCLA_1,51271,2,0,12.09,1,R,NaN,113.0,121.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.09,NaN
772,UCLA_1,51272,2,0,13.41,1,R,NaN,84.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.41,NaN
773,UCLA_1,51273,2,0,12.68,1,R,NaN,104.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.68,NaN
774,UCLA_1,51274,2,0,10.96,1,R,NaN,125.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.96,NaN
775,UCLA_1,51275,2,0,15.74,1,R,NaN,106.0,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.74,NaN
776,UCLA_1,51276,2,0,13.85,1,R,NaN,105.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.03,NaN
781,UCLA_1,51281,2,0,11.83,1,R,NaN,108.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.91,NaN
796,UCLA_2,51304,2,0,10.53,1,R,NaN,120.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.53,NaN
798,UCLA_2,51306,2,0,11.66,1,R,NaN,119.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.66,NaN
799,UCLA_2,51307,2,0,12.15,1,R,NaN,128.0,127.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.15,NaN
800,UCLA_2,51308,2,0,9.79,1,R,NaN,124.0,125.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.08,NaN
802,UCLA_2,51310,2,0,11.70,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,-9999.00,NaN
803,UCLA_2,51311,2,0,11.95,1,R,NaN,103.0,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.95,NaN
804,UCLA_2,51312,2,0,12.90,1,R,NaN,123.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.90,NaN
805,UCLA_2,51313,2,0,13.36,1,R,NaN,112.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.36,NaN
806,UCLA_2,51314,2,0,13.12,1,R,NaN,97.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.12,NaN
807,UCLA_2,51315,2,0,13.63,1,R,NaN,118.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.63,NaN
808,UCLA_2,51316,2,0,12.66,1,L,NaN,94.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.66,NaN
223,MAX_MUN,51356,2,0,10.00,1,R,NaN,129.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
224,MAX_MUN,51357,2,0,11.00,1,R,NaN,110.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
225,MAX_MUN,51358,2,0,10.00,1,R,NaN,113.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
226,MAX_MUN,51359,2,0,13.00,1,R,NaN,101.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
228,MAX_MUN,51361,2,0,16.00,1,R,NaN,114.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
31,CALTECH,51487,2,0,17.00,1,R,NaN,113.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN

In [836]:
matched_df_AUT

,SITE_ID,SUB_ID,DX_GROUP,DSM_IV_TR,AGE_AT_SCAN,SEX,HANDEDNESS_CATEGORY,HANDEDNESS_SCORES,FIQ,VIQ,...,WISC_IV_BLK_DSN_SCALED,WISC_IV_PIC_CON_SCALED,WISC_IV_MATRIX_SCALED,WISC_IV_DIGIT_SPAN_SCALED,WISC_IV_LET_NUM_SCALED,WISC_IV_CODING_SCALED,WISC_IV_SYM_SCALED,EYE_STATUS_AT_SCAN,AGE_AT_MPRAGE,BMI
489,PITT,50002,1,1,16.77,1,Ambi,NaN,103.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
493,PITT,50006,1,1,13.37,1,L,NaN,109.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
494,PITT,50007,1,1,17.78,1,R,NaN,110.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
498,PITT,50011,1,1,16.93,1,L,NaN,111.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
500,PITT,50013,1,1,9.33,1,R,NaN,86.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
501,PITT,50014,1,1,14.20,1,R,NaN,96.0,97.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
502,PITT,50015,1,1,14.20,1,R,NaN,99.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
507,PITT,50022,1,1,16.99,1,R,NaN,119.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
511,PITT,50026,1,1,16.28,1,R,NaN,87.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
512,PITT,50027,1,1,12.24,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
513,PITT,50028,1,1,12.74,1,R,NaN,126.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
515,PITT,50053,1,1,12.03,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
516,PITT,50055,1,1,16.99,1,R,NaN,111.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
517,PITT,50056,1,1,13.59,1,R,NaN,113.0,101.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
577,SDSU,50183,1,1,14.14,1,R,NaN,139.0,128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
586,SDSU,50192,1,1,12.99,1,R,NaN,85.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
659,TRINITY,50239,1,1,17.03,1,R,NaN,97.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
661,TRINITY,50241,1,1,17.17,1,R,NaN,89.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
662,TRINITY,50242,1,1,12.75,1,R,NaN,117.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
663,TRINITY,50243,1,1,13.75,1,R,NaN,90.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
668,TRINITY,50248,1,1,13.58,1,R,NaN,117.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
669,TRINITY,50249,1,1,13.83,1,R,NaN,98.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
670,TRINITY,50250,1,1,13.91,1,R,NaN,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
671,TRINITY,50251,1,1,17.25,1,R,NaN,122.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
810,UM_1,50272,1,1,14.20,1,R,NaN,98.5,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
811,UM_1,50273,1,1,16.80,1,R,NaN,112.5,109.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
812,UM_1,50274,1,1,14.20,1,R,NaN,111.5,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
813,UM_1,50275,1,1,11.50,1,L,NaN,85.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
815,UM_1,50277,1,1,15.40,1,L,NaN,107.5,96.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
817,UM_1,50279,1,1,12.20,1,R,NaN,87.5,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
722,UCLA_1,51222,1,1,11.81,1,R,NaN,113.0,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.81,NaN
725,UCLA_1,51225,1,1,12.33,1,R,NaN,111.0,119.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.33,NaN
729,UCLA_1,51229,1,1,14.59,1,R,NaN,95.0,115.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.59,NaN
731,UCLA_1,51231,1,1,10.28,1,R,NaN,103.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.01,NaN
732,UCLA_1,51232,1,1,15.79,1,R,NaN,89.0,94.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
733,UCLA_1,51233,1,1,12.75,1,R,NaN,79.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
734,UCLA_1,51234,1,1,10.91,1,R,NaN,87.0,93.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.91,NaN
735,UCLA_1,51235,1,1,10.67,1,R,NaN,132.0,130.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.67,NaN
736,UCLA_1,51236,1,1,12.42,1,R,NaN,89.0,85.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.42,NaN
737,UCLA_1,51237,1,1,17.40,1,R,NaN,100.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,17.40,NaN
738,UCLA_1,51238,1,1,10.85,1,R,NaN,73.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.64,NaN
740,UCLA_1,51240,1,1,14.96,1,R,NaN,121.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15.40,NaN
741,UCLA_1,51241,1,1,10.90,1,R,NaN,95.0,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11.03,NaN
744,UCLA_1,51244,1,1,13.09,1,R,NaN,-9999.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
747,UCLA_1,51247,1,1,11.97,1,R,NaN,118.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
748,UCLA_1,51248,1,1,13.50,1,R,NaN,110.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.50,NaN
783,UCLA_2,51291,1,1,16.47,1,R,NaN,86.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,16.63,NaN
784,UCLA_2,51292,1,1,12.24,1,R,NaN,75.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.24,NaN
786,UCLA_2,51294,1,1,11.70,1,R,NaN,87.0,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.06,NaN
787,UCLA_2,51295,1,1,10.04,1,L,NaN,108.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.33,NaN
789,UCLA_2,51297,1,1,14.27,1,L,NaN,88.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.27,NaN
790,UCLA_2,51298,1,1,10.57,1,R,NaN,118.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.69,NaN
791,UCLA_2,51299,1,1,14.77,1,R,NaN,104.0,106.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.77,NaN
792,UCLA_2,51300,1,1,14.08,1,L,NaN,92.0,104.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14.08,NaN
793,UCLA_2,51301,1,1,13.28,1,R,NaN,91.0,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,13.28,NaN
794,UCLA_2,51302,1,1,10.85,1,R,NaN,87.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10.85,NaN
809,UCLA_2,51317,1,1,12.82,1,R,NaN,102.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12.82,NaN
217,MAX_MUN,51350,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
218,MAX_MUN,51351,1,1,11.00,1,R,NaN,79.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN
16,CALTECH,51472,1,1,17.50,1,Ambi,NaN,125.0,123.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN